# Matrices and vectors
A **list** in Python is an **ordered, mutable collection** of items.

- **Ordered**: items keep their position (index).
- **Mutable**: you can change it after creation (add, remove, or update elements).
- It can store different data types in the same collection.

In [129]:
# Demonstrate a Python list
my_list = [1, "apple", 3.14, True]

print("Original list:", my_list)
print("First item:", my_list[0])

# Lists are mutable
my_list.append("new item")
my_list[1] = "orange"

print("Updated list:", my_list)
print("Length:", len(my_list))

Original list: [1, 'apple', 3.14, True]
First item: 1
Updated list: [1, 'orange', 3.14, True, 'new item']
Length: 5


# NumPy arrays
A **NumPy array** (`ndarray`) is a fast, structured container for numerical data.

- **Homogeneous type**: all elements are stored as the same data type (for example, all integers or all floats).
- **Fixed size**: once created, its size does not change (unlike a Python list).
- **Efficient storage**: data is stored in contiguous memory, making operations faster.
- **Vectorized operations**: arithmetic is applied to all elements at once, without manual loops.
- **Supports dimensions**: arrays can be 1D (vector), 2D (matrix), or higher-dimensional.

Compared to Python lists, NumPy arrays are typically much faster and more convenient for mathematical and scientific computing.

> **IMPORTANT** When working in the lab we will mostly rely on NumPy arrays since they are more efficient and can effectively represent the data that is of interest to us (sensor readings, robot locations, etc.).

See below for different initialization of *NumPy* arrays

In [130]:
import numpy as np

# Two random 3x2 arrays and their sum
A = np.random.rand(3, 2)
B = np.random.rand(3, 2)

print("A:\n", A)
print("B:\n", B)

# Two 3x1 unit vectors
x = np.array([1.0, 0.0, 0.0])
y = np.array([0.0, 1.0, 0.0])

A:
 [[0.06335977 0.44373609]
 [0.18965705 0.75062001]
 [0.36508588 0.81793543]]
B:
 [[0.10862835 0.99417722]
 [0.39419335 0.53842622]
 [0.5454175  0.84897384]]


Now we will use the arrays to demonstrate common operations:

In [131]:
# Addition
C = A + B
print("A + B:\n", C)

# Element-wise operations
alpha_1 = 2.0
A_scaled = alpha_1 * A
print(f"\n{alpha_1} * A:\n", A_scaled)

# Dot and cross products
dot_xy = x.T @ y
cross_xy = np.cross(x, y)

print("\nx:\n", x)
print("y:\n", y)
print("dot(x, y):", dot_xy)
print("cross(x, y):\n", cross_xy)

A + B:
 [[0.17198812 1.4379133 ]
 [0.58385039 1.28904624]
 [0.91050338 1.66690928]]

2.0 * A:
 [[0.12671954 0.88747218]
 [0.3793141  1.50124003]
 [0.73017176 1.63587087]]

x:
 [1. 0. 0.]
y:
 [0. 1. 0.]
dot(x, y): 0.0
cross(x, y):
 [0. 0. 1.]


## Shape, indexing, and `:` slicing

Every NumPy array has a `.shape` attribute that returns `(rows, cols)` for a 2D array — **row index always comes first**.

Elements are accessed with zero-based indices: `M[row, col]`.  
The colon `:` means *all elements along that axis*:
- `M[:, 0]` — every row, column 0 (the entire first column)
- `M[0, :]` — row 0, every column (the entire first row)


In [132]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
], dtype=float)

print("M:\n", M)
print("Shape of M:", M.shape)       # (3, 3): 3 rows, 3 columns
print("M[0, 2]:", M[0, 2])          # row 0, column 2
print("First column M[:, 0]:", M[:, 0])   # all rows, column 0
print("Last row   M[2, :]:",   M[2, :])   # row 2, all columns

M:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Shape of M: (3, 3)
M[0, 2]: 3.0
First column M[:, 0]: [1. 4. 7.]
Last row   M[2, :]: [7. 8. 9.]


### Mission

There is a neat connection between colon indexing and matrix-vector multiplication: multiplying a matrix by a **standard basis vector** $e_i$ — a vector with a 1 at position $i$ and 0s elsewhere — extracts the $i$-th column, giving the same result as `M[:, i]`.

$$M \, e_i = M[:, i]$$

Using the matrix `M` defined above:
1. Extract the **third column** (index 2) using `:` indexing.
2. Build the standard basis vector `e3 = [0, 0, 1]` and compute `M @ e2`.
3. Verify both results are equal using `np.allclose`.

> Similarly, we can also extract rows by multiplying with a transposed unit vector from the left:
> $$e_i^\top M = M[i, :]$$

In [133]:
# 1. Third column via colon indexing
col_indexing = M[:, 2]

# 2. Third column via matrix-vector product with standard basis vector
e3 = np.array([0, 0, 1])
col_matvec = M @ e3

print("Third column via indexing:    ", col_indexing)
print("Third column via M @ e3:      ", col_matvec)
print("Are they equal?", np.allclose(col_indexing, col_matvec))

Third column via indexing:     [3. 6. 9.]
Third column via M @ e3:       [3. 6. 9.]
Are they equal? True


### Mission
1. Extract the **third row** (index 2) using `:` indexing.
2. Use the same `e2 = [0, 0, 1]` and compute `e2 @ M`.
3. Verify both results are equal using `np.allclose`.

In [134]:
# 1. Third row via colon indexing
row_indexing = M[2, :]
# 2. Third row via vector-matrix product with standard basis vector
e2 = np.array([0, 0, 1])
row_matvec = e2 @ M 
print("Third row via indexing:       ", row_indexing)
print("Third row via e2 @ M:        ", row_matvec)
print("Are they equal?", np.allclose(row_indexing, row_matvec))

Third row via indexing:        [7. 8. 9.]
Third row via e2 @ M:         [7. 8. 9.]
Are they equal? True


### Mission
As you have seen in the examples above the scalar product and addition operators are defined by `*` and `+`. Let's use our function from the previous notebook `update_dynamics` but now instead of passing a position or velocity in `x` we will pass NumPy arrays representing both dimensions. 
Use a loop to move for `1.0` seconds from `(0.0,0.0,0.0)` with a velocity of `(1.0, 0.5,0.0)`. You should:
- Store the positions at every time step into an array called `positions`.
- Store the timesteps into an array called `timesteps`. Use the `np.linspace` method to create it.
- Your end position should be `(1,0.5)`
- You should use NumPy arrays not lists or tuples

`np.linspace(start, stop, num)` creates a NumPy array of `num` evenly spaced values from `start` to `stop` (including both endpoints by default).

It is useful because it:

- Generates **uniform time grids** (for example, simulation timesteps).
- Avoids manually computing step values in loops.
- Returns a **NumPy array**, so it works directly with vectorized math and plotting.
- Makes code clearer and less error-prone when you need a fixed number of samples (like positions over `1.0` second).

In [135]:
# Copying function definition
def update_dynamics(current_position_x, velocity_x, dt):
    # Simple dynamics update: new_position = old_position + velocity * time_step
    new_position_x = current_position_x + velocity_x * dt
    return new_position_x

x0 = np.array([0.0, 0.0, 0.0])  # Initial position
v = np.array([1.0, 0.5, 0.0])   # Velocity in x and y
dt = 0.1                    # Time step in seconds

t_end = 1.0
N = int(t_end / dt)
positions = np.zeros((N, 3))  # To store positions at each time
times = np.linspace(0, t_end, N)  # Time array for plotting
positions[0] = x0

for i in range(N):
    positions[i] = update_dynamics(positions[i-1], v, dt)
print("\nPositions over time:\n", positions)


Positions over time:
 [[0.1  0.05 0.  ]
 [0.2  0.1  0.  ]
 [0.3  0.15 0.  ]
 [0.4  0.2  0.  ]
 [0.5  0.25 0.  ]
 [0.6  0.3  0.  ]
 [0.7  0.35 0.  ]
 [0.8  0.4  0.  ]
 [0.9  0.45 0.  ]
 [1.   0.5  0.  ]]


### Homogeneous transformation matrix (quick reminder)

In robotics, we often want to represent **rotation and translation together** in one matrix.  
A homogeneous transform does exactly that:

$$
\textbf{T}= \begin{bmatrix}
\mathbf{R} & \mathbf{t} \\
\mathbf{0}^{\top} & 1
\end{bmatrix}
$$

- $\mathbf{R}$: rotation matrix  
- $\mathbf{t}$: translation vector

For a 3D pose ($SE(3)$):

$$
\textbf{T} = \begin{bmatrix}
r_{11} & r_{12} & r_{13} & t_x \\
r_{21} & r_{22} & r_{23} & t_y \\
r_{31} & r_{32} & r_{33} & t_z \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

---

For planar robots ($SE(2)$, 2D motion), we use:

$$
\mathbf{T_{2D}} =
\begin{bmatrix}
\cos\theta & -\sin\theta & t_x \\
\sin\theta & \cos\theta  & t_y \\
0 & 0 & 1
\end{bmatrix}
$$

---

Useful properties:

1. **Composition** (chain transforms):

$$
\mathbf{T}_{ac}=\mathbf{T}_{ab}\mathbf{T}_{bc}
$$

2. **Inverse**:

$$
\mathbf{T}^{-1}=
\begin{bmatrix}
\mathbf{R}^\top & -\mathbf{R}^\top\mathbf{t}\\
\mathbf{0}^\top & 1
\end{bmatrix}
$$

This is why homogeneous matrices are central in robotics: they provide a compact way to move between coordinate frames.

### Example: rotating a point into a drone's body frame

Suppose our Crazyflie is sitting at the **origin** but has rotated **45°** (yaw).  
A landmark is at `[1, 0]` in the world frame — 1 m along the world x-axis.  
Where does that landmark appear relative to the drone?

We build the SE(2) transform `T_world_drone` (the drone's pose in the world frame), invert it to get `T_drone_world`, then apply it to the landmark.

In [136]:
import numpy as np

# Drone pose: yaw = 45°, no translation (sitting at origin)
yaw = np.deg2rad(45)
tx, ty = 0.0, 0.0

T_world_drone = np.array([
    [np.cos(yaw), -np.sin(yaw), tx],
    [np.sin(yaw),  np.cos(yaw), ty],
    [0,            0,           1 ]
])

# Landmark in world frame (homogeneous coordinates)
p_world = np.array([1.0, 0.0, 1.0])

# Inverse: world frame → drone body frame
T_drone_world = np.linalg.inv(T_world_drone)
p_body = T_drone_world @ p_world

print("Drone yaw: 45°, at origin")
print("Landmark in world frame:     ", p_world[:2])
print("Landmark in drone body frame:", np.round(p_body[:2], 4))
# Result: [cos(-45°), sin(-45°)] ≈ [0.707, -0.707]
# The landmark is ahead-right in the drone's rotated frame

Drone yaw: 45°, at origin
Landmark in world frame:      [1. 0.]
Landmark in drone body frame: [ 0.7071 -0.7071]


### Mission

A Crazyflie drone is flying in the world frame. It has landed at position `[0.5, 0.5]` (in metres) and rotated to a yaw of **90°**. A landmark is located at `[1.0, 0.0]` in the world frame.

Your task:
1. Build the SE(2) homogeneous transform `T_world_drone` that describes the drone's pose in the world frame (yaw = 90°, translation = [0.5, 0.5]).
2. Express the landmark `p_world = [1.0, 0.0]` in **homogeneous coordinates** (append a 1).
3. Compute the inverse transform `T_drone_world` and use it with the `@` operator to find where the landmark appears in the drone's body frame.

Hints: `np.cos`, `np.sin`, `np.deg2rad`, `np.linalg.inv`, `@`

In [137]:
import numpy as np

# Drone pose in world frame: yaw = 90 degrees, position = [0.5, 0.5]
yaw = np.deg2rad(90)
tx, ty = 0.5, 0.5

# SE(2) homogeneous transform: T_world_drone
T_world_drone = np.array([
    [np.cos(yaw), -np.sin(yaw), tx],
    [np.sin(yaw),  np.cos(yaw), ty],
    [0,            0,           1 ]
])

# Landmark position in world frame (homogeneous coordinates)
p_world = np.array([1.0, 0.0, 1.0])

# Express landmark in drone body frame
T_drone_world = np.linalg.inv(T_world_drone)
p_body = T_drone_world @ p_world

print("T_world_drone =\n", np.round(T_world_drone, 4))
print("Landmark in world frame:      ", p_world[:2])
print("Landmark in drone body frame: ", np.round(p_body[:2], 4))
# Expected: [-0.5, -0.5]
# The drone faces +y at 90° yaw, so the landmark (world x=1) is
# 0.5 m behind the drone and 0.5 m to its right in body frame.

T_world_drone =
 [[ 0.  -1.   0.5]
 [ 1.   0.   0.5]
 [ 0.   0.   1. ]]
Landmark in world frame:       [1. 0.]
Landmark in drone body frame:  [-0.5 -0.5]
